name: Build + Publish Game

on:
  push:
    branches: main

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Bump version and tag
        id: bump
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: version
      - name: Push commit and tag
        run: git push
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac, web]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.set-version.output.new_tag }}
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: godot-to-itch-demo
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Godot To Itch Demo - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.platform }}
          ITCH_GAME: godot-to-itch-demo
          ITCH_USER: tfinch
          PACKAGE: ${{ github.workspace }}/${{ steps.build.outputs.build }}
