name: Create next version + tag

on:
  push:
    branches: main
    tags-ignore: "*"

jobs:
  godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Bump version and tag
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: version
      - name: Push commit and tag
        run: git push
